# -*- coding: utf-8 -*-
"""Aula1-Caderno-Alura

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e6qIZ6wilLDOhytOyhXqiMQqN0UANWDP

Para podermos importar um valor de um csv, é preciso importar a biblioteca pandas, após isso é necessário criar uma variável que receba esses valores.
"""

import pandas as pd
dados = pd.read_csv('https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true',compression = 'zip')
dados

dados.head()

"""dados.shape <-- utilizado para saber o tamanho do conjunto de dados (linhas,colunas)

"""

dados.shape

dados['tratamento']

"""dados['nome_da_coluna'].unique() <-- Permite verificar quais os valores que aparecem ao longo da coluna.

"""

dados['tratamento'].unique()

dados['tempo'].unique()

dados['dose'].unique()

dados['droga'].unique()

dados['g-0'].unique()

"""dados['nome_da_coluna'].value_counts() <-- Retorna a quantidade de elementos em cada possível valor da minha coluna"""

dados['tratamento'].value_counts()

dados['dose'].value_counts()

dados['tratamento'].value_counts().plot.pie()

dados['tempo'].value_counts(normalize = True).plot.pie()

"""Não é interessante utilizar o gráfico de pizza para analisar os dados que estão muito próximos, ou melhor, que estão balanceados, por isso pode-se utilizar outros tipos de gráfico, como o de barra."""

dados['tempo'].value_counts().plot.bar()

dados_filtrados = dados[dados['g-0'] > 0]

dados_filtrados.head()

"""###**Desafio 1: Investigar por que a classe tratamento é tão desbalanceada?**
###**Desafio 2: Plotar as 5 últimas linhas da tabela.**
###**Desafio 3: Proporção das classes tratamento.**
###**Desafio 4: Quantos tipos de drogas foram investigados.**
###**Desafio 5: Procurar na documentação o método query (pandas).**
###**Desafio 6: Renomear as colunas tirando o hífen.**
###**Desafio 7: Deixar os gráficos bonito. (Com matplotlib)**
###**Desafio 8: Resumo do que você aprendeu com os dados**


"""

